language: objective-c
osx_image: xcode8.3

script:
  - open -a "simulator" --args -CurrentDeviceUDID 482F5B24-39BD-44E0-A525-8AA39234DA28
  - xcodebuild clean build test -project WARPServices.xcodeproj -scheme WARPServices -destination 'platform=iOS Simulator,OS=10.3.1,id=482F5B24-39BD-44E0-A525-8AA39234DA28'

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: true
