language: objective-c
osx_image: xcode9

script:
  - xcodebuild clean build test -project WARPServices.xcodeproj -scheme WARPServices -destination 'platform=iOS Simulator,OS=11.0,name=iPhone 8 Plus'

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: true
